### ISSUE TITLE
Describe undocumented item-identifier based URL access

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/iso-geodetic-register-docs#2]
According to Florian, the URL pattern

`https://registry.isotc211.org/register/geodetic/items/<itemIdentifier>`

Where `<itemidentifier>` is:

<img width="445" alt="Screen Shot 2019-05-23 at 12 09 45 AM" src="https://user-images.githubusercontent.com/11865/58190432-143bc480-7cef-11e9-9324-9258896a0398.png">

will redirect to the UUID-based URL.

i.e.
https://registry.isotc211.org/register/geodetic/items/209

Will redirect to:
https://registry.isotc211.org/item/a7605446-a937-418f-9114-73b4883d0e9b

This issue is to describe this in the user guide.

Florian also says:
> It's not possible at the moment, unfortunately, to reference the WKT or
XML representations in that way. Support for that would be fairly simple
to implement, though.

**Comment by maccraymer** [comment]
@ronaldtse replied to my response to an email from Simon Cox about this issue. I have the URL pattern wrong. The current pattern for the redirect is now (registry.isotc211.org is replaced by geodetic.isotc211.org):

     https://geodetic.isotc211.org/register/geodetic/items/284

Note that the following alternate form of the basic part of the domain name (geodetic.isotc211.org replaced by registry.isotc211.org/geodetic) does not work with the redirect; i.e.,

     https://registry.isotc211.org/geodetic/register/geodetic/items/284

It always redirects to https://geodetic.isotc211.org/.

I am closing this issue as the alternate form of the redirect is not really necessary and I think we should be promoting only geodetic.isotc211.org which does work.
